version: "3.8"

services:

  bot:
    build: .
    command: sh -c "python -m bot"
    container_name: club-bot
    volumes:
      - .:/bot
    env_file:
      - .env.bot
    restart: always
    depends_on:
      - postgres

  admin:
    build: .
#    command: sh -c "alembic revision --autogenerate && alembic upgrade head && python -m admin"
    command: sh -c "python -m admin"
    container_name: club-admin
    ports:
      - "8050:8000"
    volumes:
      - .:/bot
    env_file:
      - .env.bot
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine3.18
    container_name: club-db
    env_file:
      - .env.postgres
    restart: always

#  dj:
#    build: .
#    command: sh -c "cd dj && python manage.py runserver 0.0.0.0:8000 && python manage.py makemigrations && django-admin inspectdb > admin_app/models.py "
#    container_name: dj-admin
#    ports:
#      - "8070:8000"
#    volumes:
#      - .:/bot
#    env_file:
#      - .env.bot
#    restart: always
#    depends_on:
#      - postgres